name: libflutter_missing_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: 1.0.3
  mvc_pattern: 6.3.0
  global_configuration: 1.6.0
  http: 0.12.2
  html: 0.14.0+4
  shared_preferences: ^0.5.12+2
  flutter_html: 1.0.2
  location: 3.0.2
  url_launcher: 5.7.7
  cached_network_image: 2.3.3
  fluttertoast: ^4.0.0
  intl_utils: 1.8.0
  cloud_firestore: 0.14.1+3
  firebase_messaging: ^7.0.0
  firebase_auth: 0.18.1+2
  firebase_core: 0.5.0+1
  flutter_launcher_icons: ^0.8.1
  sentry_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

